# Generated by Django 4.2.5 on 2023-09-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringsummary',
            name='created_at',
            field=models.DateField(),
        ),
    ]
