# Generated by Django 4.2.5 on 2023-10-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_summaries', '0002_alter_engineeringsummary_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineeringsummary',
            name='author',
        ),
    ]
