# Generated by Django 4.2.6 on 2024-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_summaries', '0003_remove_engineeringsummary_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
